# Generated by Django 4.2.1 on 2023-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='stat',
            field=models.CharField(choices=[('Опубликовано', 'Опубликовано'), ('Заблокировано', 'Заблокировано'), ('Снято с публикации', 'Снято с публикации'), ('На модерации', 'На модерации')], help_text='Выберите состояние добавленного обьекта', max_length=200, verbose_name='Состояние'),
        ),
    ]
