# Generated by Django 4.2.1 on 2023-06-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('buildings', '0003_alter_status_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(help_text='Выберите контактное лицо/владельца обьекта', on_delete=django.db.models.deletion.DO_NOTHING, related_name='buildings', to='users.landlord', verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(help_text='Введите дату начала аренды', verbose_name='Дата начала аренды')),
                ('check_out', models.DateField(help_text='Введите дату окончания аренды', verbose_name='Дата окончания аренды')),
                ('message', models.TextField(blank=True, help_text='Введите текст сообщения', verbose_name='Сообщение владельцу')),
                ('approve', models.BooleanField(default=False, help_text='Подтвердил или нет бронь владелец', verbose_name='Подтверждение владельца')),
                ('building', models.ForeignKey(help_text='Выберите обьект', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings_object', to='buildings.building', verbose_name='Объект')),
                ('owner', models.ForeignKey(help_text='Выберите владельца обьекта', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings_owner', to='users.landlord', verbose_name='Владелец объекта')),
                ('renter', models.ForeignKey(help_text='Выберите арендатора обьекта', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings_renter', to='users.renter', verbose_name='Арендатор объекта')),
            ],
        ),
    ]
