# Generated by Django 4.2.1 on 2023-06-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_alter_building_owner_bookings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='owner',
        ),
    ]
