# Generated by Django 4.2.1 on 2023-06-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_alter_bookings_options_remove_bookings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.BooleanField(default=False, help_text='Рассмотрел или нет заявку владелец', verbose_name='Рассмотрение владельцем'),
        ),
    ]
